# Generated by Django 2.0.1 on 2018-02-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pipes_blog', '0002_auto_20180202_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
