# Generated by Django 2.0.1 on 2018-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pipes_blog', '0003_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(default='image-name', max_length=255),
            preserve_default=False,
        ),
    ]
