# Generated by Django 2.0.1 on 2018-02-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pipes_blog', '0004_postimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
